name: Upload IPA to App Store

on:
  workflow_dispatch: # 手动触发
  # push:
  #   branches:
  #     - main           # push 自动触发（可选）

  env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ✅ 强制用 Node 24


jobs:
  upload:
    runs-on: macos-latest # ⚠️ 必须 macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install fastlane
        run: gem install fastlane -NV

      - name: Upload IPA
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT: true
          FASTLANE_ITUNES_TRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS: "-t DAV"
        run: fastlane upload
